### ISSUE TITLE
Will this work with TM Web 2.0?

### ISSUE THREAD

**Issue by wallyatkins** [rogergrambihler/troopmaster#1]
I was curious to see if you still work with TroopMaster at all or not and if you have played with TroopMaster Web 2.0.

From what I have seen they only offer a hosted database solution now and the only way to retrieve your information is from dynamically generated web reports.

**Comment by rogergrambihler** [comment]
I have not tried out Troopmaster web. TroopMaster is still offering the desktop troopMaster. http://www.troopmaster.com/downloads/Setup_TM2015.exe

**Comment by wallyatkins** [comment]
Well, just a heads up then. If you do migrate to TM Web it's the last time you will have your database reside locally. I'm personally on the search for how to work/interact with our troop's data via TM Web. I appreciate your time and response!
